2018 03 10 tar perm roles p1 t2
ridz1208/Loris pull request #13
Opened 2018-04-23 18:21 UTC by ridz1208

This pull request `[DESCRIBE WHAT THIS PULL REQUEST IS TRYING TO ACCOMPLISH HERE]`. It `[DESCRIBE HOW IT ACCOMPLISHES THE GOAL HERE]`.

See also: `[PROVIDE REFERENCES TO OTHER TICKETS, PULL REQUESTS, OR MAILING LIST THREADS HERE. OPTIONAL.]`

2018-04-25 13:49 UTC, xlecours requested changes
A few things but I think we should look at a bigger picture here. I thought the permission controler would add/remove permission(s) to a user or role. Doign so it would expect a User or a Role and an array of permission to deal with. Maybe we should talk face to face.

2018-04-25 13:56 UTC, ridz1208 commented
@xlecours yes it's right it should be and they will be added below that whitespace gap. lets talk when you want

2018-04-26 23:43 UTC, ridz1208 commented on php/libraries/Permission.class.inc
> +        // Limit accessibility to this value.
immutability seems very complex to me in this cintext I think we can sit Dave, Melanie, you and I and whoever else is intersted and discuss it in this context but for now the most critical element is the ID

2018-04-26 23:44 UTC, ridz1208 commented on php/libraries/PermissionController.class.inc
> +    function __construct(Database $database)
sure

2024-01-25 13:41 UTC, closed without merging